version: "3.4"
services:
  pathfinder.public.dappnode.eth:
    build:
      context: build/.
      args:
        UPSTREAM_VERSION: v0.1.6-alpha
    image: "pathfinder.public.dappnode.eth:0.1.0"
    ports:
      - "9545:9545"
    environment:
      RUST_LOG: info
      ETH_RPC_URL: "http://geth.dappnode:8545"
      EXTRA_OPTIONS: ""
    volumes:
      - "pathfinder_data:/usr/share/pathfinder/data"
    restart: unless-stopped
volumes:
  pathfinder_data: {}
